name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gsl
      run: sudo apt-get install -y libgsl-dev
    - uses: actions/checkout@v3
    - name: make
      run: ./BDHM/make
